sudo: required
services:
  - docker

before_install:
  -docker build -t sprab/react-test -f ./client/Dockerfile.dev ./client

script:
  -docker run sprab/react-test npm test -- --coverage

after_success:
  - docker build -t sprab/multi-client -f ./client
  - docker build -t sprab/multi-nginx -f ./nginx
  - docker build -t sprab/multi-server -f ./server
  - docker build -t sprab/multi-worker -f ./worker

  # Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push it to docker hub.
  - docker push -t sprab/multi-client
  - docker push -t sprab/multi-nginx
  - docker push -t sprab/multi-server
  - docker push -t sprab/multi-worker

